### ISSUE TITLE
Flow type checking does not accept string literals for RPC id

### ISSUE THREAD

**Issue by ksheedlo** [fusionjs/fusion-rpc-redux#67]
### Type of issue

bug

### Description

flow type checking fails when I use a string literal as the RPC name. I want it to succeed.

### Current behavior

Flow type checking fails when I use a string literal as the RPC name

```
┌─[ken][ksheedlo-C02RC1GZG8WM][±][add-get-template-rpc U:5 ?:1 ✗][~/unpm-code/web-search-emoji]
└─▪ yam flow
yarn run v1.3.2
$ flow check
Error: src/reducers/template.js:41
 41: const getTemplateRPCReducer = createRPCReducer('getTemplate', {
                                                    ^^^^^^^^^^^^^ string. This type is incompatible with the expected param type of
 43:   rpcId: String,
              ^^^^^^ String. See: node_modules/fusion-rpc-redux/src/index.js:43


Found 1 error
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Expected behavior

```
┌─[ken][ksheedlo-C02RC1GZG8WM][±][add-get-template-rpc U:6 ?:1 ✗][~/unpm-code/web-search-emoji]
└─▪ yam flow
yarn run v1.3.2
$ flow check
Found 0 errors
✨  Done in 4.70s.
```

### Steps to reproduce

1. Import `createRPCReducer`
2. Call it in a flow file as `createRPCReducer('stringLiteral', { ... })`
3. Run a flow typecheck

### Your environment

* fusion-rpc-redux version: 1.0.1

* Node.js version (`node --version`): v8.9.4

* npm version (`npm --version`): 5.6.0 (I'm using Yarn)

* Operating System: macOS 10.13.3

**Comment by KevinGrandon** [comment]
Great bug report 🎉
