### ISSUE TITLE
Wrapping createRPCReducer with another function will make error swallowed

### ISSUE THREAD

**Issue by ardok** [fusionjs/fusion-rpc-redux#81]
### Type of issue

Bug

### Description

```
function withAuthCheck(originalHandler) {
  return (state, action) => {
    const {noExistLa} = action;
    // TODO no error, wtf?
    if (noExistLa.whatever) {
      return {};
    }
    return originalHandler(state, action);
  };
}

export default reduceReducers(
  (state) => state || someDefaultState,
  createRPCReducer(rpcIds.rpcGetDashboards, {
    start: ...,
    success: withAuthCheck((state, action) => {
      return {
        ...state,
      };
    }),
    failure: ...,
  }),
);
```

There's no error saying that can't get 'whatever' from undefined or anything at all.
Everything just runs like normally.

### Current behavior

No error. Everything just runs.

### Expected behavior

An error should have been thrown.

### Steps to reproduce

Provided code example above.

### Your environment

* fusion-rpc-redux version: ^1.0.2

* Node.js version (`node --version`): 8.11.1

* npm version (`npm --version`): 5.6.0

* Operating System: MacOS 10.13.4

**Comment by cgvedant** [comment]
Looks like there's a problem in createRPCHandler. Your error is being caught [here](https://github.com/fusionjs/fusion-rpc-redux/blob/master/src/index.js#L160) and the error message being sent to the failure(). I'm not sure what the intended use of failure was because it doesn't seem to catch errors in the rpc call. Maybe @lhorie can shed some light on this issue.

**Comment by steponas** [comment]
I agree that it's a design problem. 

Now if Fusion RPC call returns an error, it's caught in `createRPCHandler` (same line as @cgvedant mentioned) and returns a resolved promise. So the only way to check for error response is to do a blind-folded touching of the object for `code, message and meta` fields being there.

I really hope this gets changed. I understand that it might be a breaking change though it's worth it (c).

cc/ @KevinGrandon

**Comment by cgvedant** [comment]
I feel separating the success reducer would be the best option. Failure reducer should only concern itself with any failure in the RPC. Errors in success reducer should be treated as any other error in the server. Deleting the error stack could make things hard to debug.
